services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./books:/books:ro
      - ./config.json:/app/config.json:ro
      - ./templates:/app/templates:ro
    ports:
      - 8080:8080
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=dev