services:
  app:
    build: .
    volumes:
      - ./books:/books:ro
      - ./config.json:/app/config.json:ro
    ports:
      - 8080:8080
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=dev